baseURL = "https://www.ivankovic.me/"
languagecode = "en-US"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[languages]
  [languages.en]
    title = "Ivanković family website"
  [languages.hr]
    title = "Web stranica obitelji Ivanković"
  [languages.de]
    title = "Die Website der Familie Ivanković"

[Params]
    names = ["marko", "marina"]

[languages.en.params.marko]
    author = "Marko Ivanković"
    info = "Software Engineer"
    description = "Marko Ivanković"
    keywords = "blog,engineer,personal"
    avatarurl = "images/marko/sigil.png"

[languages.hr.params.marko]
    author = "Marko Ivanković"
    info = "Magistar inženjer računarstva"
    description = "Marko Ivanković"
    keywords = "blog,inženjer,osobni"
    avatarurl = "images/marko/sigil.png"

[languages.de.params.marko]
    author = "Marko Ivanković"
    info = "Master of Engineering"
    description = "Marko Ivanković"
    keywords = "blog,ingenieur"
    avatarurl = "images/marko/sigil.png"

# Social links
[[Params.global.marko.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ivankovic"
[[Params.global.marko.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate fa-2x"
    weight = 2
    url = "https://www.researchgate.net/profile/Marko_Ivankovic4"
[[Params.global.marko.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/ivankovicmarko/"
[[Params.global.marko.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/IvankovicMe"

# Menu links
[[languages.en.menu.marko]]
    name = "Blog"
    weight = 1
    url  = "/marko/blog/"
[[languages.en.menu.marko]]
    name = "About"
    weight = 2
    url = "/marko/about/"
[[languages.en.menu.marko]]
    name = "Contact me"
    weight = 3
    url = "mailto:marko@ivankovic.me"

[[languages.hr.menu.marko]]
    name = "Blog"
    weight = 1
    url  = "/marko/blog/"
[[languages.hr.menu.marko]]
    name = "O meni"
    weight = 2
    url = "/marko/about/"
[[languages.hr.menu.marko]]
    name = "Kontakt"
    weight = 3
    url = "mailto:marko@ivankovic.me"

[[languages.de.menu.marko]]
    name = "Lebenslauf"
    weight = 2
    url = "/marko/about/"
[[languages.de.menu.marko]]
    name = "Kontakt"
    weight = 3
    url = "mailto:marko@ivankovic.me"

[languages.en.params.marina]
    author = "Marina Čelar Ivanković"
    info = "Doctor of Veterinary Medicine"
    description = "Marina Čelar Ivanković"
    keywords = "veterinarian"
    avatarurl = "images/marina/sigil.png"

[languages.hr.params.marina]
    author = "Marina Čelar Ivanković"
    info = "Doktor Veterinarske Medicine"
    description = "Marina Čelar Ivanković"
    keywords = "veterinar"
    avatarurl = "images/marina/sigil.png"

[languages.de.params.marina]
    author = "Marina Čelar Ivanković"
    info = "Tierärztin"
    description = "Marina Čelar Ivanković"
    keywords = "tierärztin"
    avatarurl = "images/marina/sigil.png"

# Social links
[[Params.global.marina.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://hr.linkedin.com/in/marinacelarivankovic"

# Menu links
[[languages.en.menu.marina]]
    name = "About"
    weight = 1
    url = "/marina/about/"
[[languages.en.menu.marina]]
    name = "Contact me"
    weight = 2
    url = "mailto:marina@ivankovic.me"

[[languages.hr.menu.marina]]
    name = "O meni"
    weight = 1
    url = "/marina/about/"
[[languages.hr.menu.marina]]
    name = "Kontakt"
    weight = 2
    url = "mailto:marina@ivankovic.me"

[[languages.de.menu.marina]]
    name = "Lebenslauf"
    weight = 1
    url = "/marina/about/"
[[languages.de.menu.marina]]
    name = "Kontakt"
    weight = 2
    url = "mailto:marina@ivankovic.me"
