baseURL = "https://www.ivankovic.me/"
title = "Ivanković family website"
languagecode = "en-US"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[[params.marko]]
    author = "Marko Ivanković"
    info = "Software Engineer"
    description = "Marko Ivanković's personal website"
    keywords = "blog,engineer,personal"
    avatarurl = "images/marko/sigil.png"

# Social links
[[params.marko.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ivankovic"
[[params.marko.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/ivankovicmarko/"

# Menu links
[[menu.marko]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.marko]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.marko]]
    name = "Contact me"
    weight = 2
    url = "mailto:marko@ivankovic.me"

[[params.marina]]
    author = "Marina Čelar Ivanković"
    info = "Doctor of Veterinary Medicine"
    description = "Marina Čelar Ivanković's personal website"
    keywords = "blog,veterinarian,personal"
    avatarurl = "images/sigil.jpg"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    hidefooter = true

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.marina.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://hr.linkedin.com/in/marinacelarivankovic"

# Menu links
[[menu.marina]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.marina]]
    name = "Contact me"
    weight = 2
    url = "mailto:marina@ivankovic.me"
