baseURL = "https://www.ivankovic.me/"
title = "Ivanković family website"
languagecode = "en-US"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
    names = ["marko", "marina"]

[params.marko]
    author = "Marko Ivanković"
    info = "Software Engineer"
    description = "Marko Ivanković"
    keywords = "blog,engineer,personal"
    avatarurl = "images/marko/sigil.png"

# Social links
[[params.marko.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ivankovic"
[[params.marko.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate fa-2x"
    weight = 2
    url = "https://www.researchgate.net/profile/Marko_Ivankovic4"
[[params.marko.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/ivankovicmarko/"
[[params.marko.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/IvankovicMe"

# Menu links
[[menu.marko]]
    name = "Blog"
    weight = 1
    url  = "/marko/blog"
[[menu.marko]]
    name = "About"
    weight = 2
    url = "/marko/about/"
[[menu.marko]]
    name = "Contact me"
    weight = 2
    url = "mailto:marko@ivankovic.me"

[params.marina]
    author = "Marina Čelar Ivanković"
    info = "Doctor of Veterinary Medicine"
    description = "Marina Čelar Ivanković"
    keywords = "blog,veterinarian,personal"
    avatarurl = "images/marina/sigil.png"

# Social links
[[params.marina.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://hr.linkedin.com/in/marinacelarivankovic"

# Menu links
[[menu.marina]]
    name = "About"
    weight = 2
    url = "/marina/about/"
[[menu.marina]]
    name = "Contact me"
    weight = 2
    url = "mailto:marina@ivankovic.me"
