baseURL = "https://www.ivankovic.me/marina/"
title = "Marina Čelar Ivanković"
theme = "coder"
languagecode = "en-US"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Marina Čelar Ivanković"
    info = "Doctor of Veterinary Medicine"
    description = "Marina Čelar Ivanković's personal website"
    keywords = "blog,veterinarian,personal"
    avatarurl = "images/sigil.jpg"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    hidefooter = true

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://hr.linkedin.com/in/marinacelarivankovic"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact me"
    weight = 2
    url = "mailto:marina@ivankovic.me"
