baseURL = "https://www.ivankovic.me/marko/"
title = "Marko Ivanković"
theme = "coder"
languagecode = "en-US"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Marko Ivanković"
    info = "Software Engineer"
    description = "Marko Ivanković's personal website"
    keywords = "blog,engineer,personal"
    avatarurl = "images/sigil.png"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    hidefooter = true

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ivankovic"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/ivankovicmarko/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
